### PR TITLE
Few fixes to compile on FreeBSD 14.

### PR DESCRIPTION
**Pull request by glebius**

### CODE REVIEW

**Comment by swuensch** [comment]
Hi @glebius,

the second commit 0xa061e4d is part of pull request #19 as well. It is already merged now.

Additionally #19 passes the second parameter of if_foreach_llmaddr() as a function pointer:

`if_foreach_llmaddr(iflib_get_ifp(ctx), &aq_mc_filter_apply, softc);`

Could you please confirm that this is:
- correct in FreeBSD 13 (it was demanded by the compiler)
- still valid in FreeBSD 14

Cheers
Sven

**Comment by glebius** [comment]
Yes, this is correct. Your change in #19 doesn't change anything. Per 6.3.2.1 of C standard:

> A function designator is an expression that has function type. Except when it is the operand of the sizeof operator,66) or the unary & operator, a function designator with type "function returning type" is converted to an expression that has type "pointer to function returning type".

I'm very surprised that this change was demanded by the compiler. What was the compiler?

**Comment by swuensch** [comment]
@glebius, thanks for the clarification. I got the compiler warning under a fresh, standard FreeBSD 13 setup:

`# cc --version`
`FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)`
`Target: x86_64-unknown-freebsd13.0`
`Thread model: posix`
`InstalledDir: /usr/bin`

the compiler's error message can be found in #17

**Comment by glebius** [comment]
@swuensch this is warning about different function prototype, not about missing & before function name.

**Pull request merged**
